### ISSUE TITLE
【失敗】XML 轉 VO 物件

### ISSUE THREAD

**Issue by Gaduo** [DatacomRD/dtc-fhir#1]
轉換失敗原因：XSD 版的 DiagnosticReport.id  型態為 Id 其 annotation 為 '@XmlType(name = "id")' ，但 hapi fhir server 來的是字串，在字串與 Id 之間的轉換有問題。

轉換範例，https://gist.github.com/Gaduo/1b131058d23bb302cff6fa0e79f5b019

**Comment by MontyPan** [comment]
你做的這件事情我已經作過了，參見： https://github.com/DatacomRD/dtc-fhir/tree/master/generator ，再加上 https://github.com/DatacomRD/Forum/issues/8#issuecomment-228719937 的結果，我目前是直接放棄治療。如果要直接處理 JSON 的話，自己手工硬幹一套對應 VO set 比較實際（在 DialysisQC 已經初步弄了一部分）

不過這些跟你在 FIDXC 的 task 好像沒關係耶...  用 OO 的講法可能比較快：我希望 `Report` 是 has a `DiagnosticReport`，不是「is-a」的關係。搭配 HAPI 已經處理好 unmarshal 的部份，應該不用再去搞 JSON 之類的東西。
