### ISSUE TITLE
重整 ReferenceUtil

### ISSUE THREAD

**Issue by MontyPan** [DatacomRD/dtc-fhir#19]
* 沒有將 `Resource` 轉成 `Reference` 的方法
	* 如果沒有要給 `display`，用既有的 `convert()` 變得很無意義...
* `convert()` 的 JavaDoc 辭不達意，沒有說明 vp 是要幹麼的

**Comment by MontyPan** [comment]
應該要有 `decompose(Reference)`，而不是只有 `decompose(String)`

**Comment by ybon3** [comment]
#29
