### ISSUE TITLE
轉移 FIDXC 的實作 code

### ISSUE THREAD

**Issue by MontyPan** [DatacomRD/dtc-fhir#3]
以下是 base on FIDXC 的版本，基本上大多是提案性質（**並不是** 一定得這麼作）以及 memo 性質。
- 希望名字可以改簡單一點，目前我的提案是：
  - GenericFhirRepository→GenericGwtRepo
  - AbstractGenericHapiFhirRepository→GenericHapiRepo
  - btw... 我自己的命名習慣是比較偏向使用 "Base" 而不是 "Generic"（參見 [dtc-zk](https://github.com/DatacomRD/dtc-zk/tree/master/src/main/java/com/dtc/common/zk/viewmodel)），不過我並沒有什麼冠冕堂皇的理由說 `Base` 比 `Generic` 好，除了字數比較少、不會跟泛型混淆之外（可是你這個主要的確是要對付泛型）
- 承上，我希望 GWT 版的 repo 跟 HAPI 版的 repo 在 package 上是平行的
- `baseUrl` 設定問題
  - 我目前想到解是弄一個 factory 負責吐各個 resource repo 的 instance，所以只要對 factory 設定一次 baseUrl 就好，但是我不得不說這個想法實在... ![](http://mp.nq.hk/wp-content/uploads/2013/08/hezhishiyuchun.jpg) ，好像得不到什麼好處、沒什麼實利

目前只想到這些...... 

to @ybon3 ：有空的話也請關注這個 issue / 發表意見，畢竟你面對 @Gaduo 的這些 code 的時間還比我多
（謎之聲：從來沒有「有空」這回事！ :see_no_evil: ）

**Comment by MontyPan** [comment]
經過 ~~短暫~~ meeting 的結果，目前三人（ @ybon3 @Gaduo ）的結論如下：
- `baseUrl` 在 repo instance 建立的時候（手動）指定
  - 也就是不用那個愚蠢的 factory 招數
  - 反正現在 repo 還很少，工人智慧還撐得住
  - 有打算用 Spring 解，但是卡到 (dtc-core) `DoubleProperties` 的整合問題，所以暫時先跳過，日後再找時間解
    - 備註：理論上 Spring 可以解決 `DoubleProperties` 的需求
- 其他好像就都覺得第一個 comment 的內容沒啥問題...... :dancer: 

以上！

**Comment by Gaduo** [comment]
Spring Solution
===========
結論：依據 spring 的解法可以達到 DoubleProperties

方法如下：

1. 產生一個 static bean 為 class org.springframework.context.support.PropertySourcesPlaceholderConfigurer。

1. 設定組態檔來源，annotation 一個 property-placeholder ，location 為 properties 可為複數， ignoreResourceNotFound 設為 true。  
如範例所示的兩個組態檔其內容中的變數完全相同，差異在於環境不同，優先權以最後面 (`cardiology.linux.properties`) 為優先，當 `cardiology.linux.properties` 不存在則沿用 `cardiology.properties`。  
組態來源也可以是一個  System.properties 中的變數。  
    ```
    <context:property-placeholder location="classpath:cardiology.properties,classpath:cardiology.linux.properties,${var}.properties"  ignore-resource-not-found="true"/>
    ```

1. 注射 properties value，寫法如下，相當於 @Autowired 

 建構完畢才相依性注射  
    ```
    @Value("${path}")   
    private String path;  
    ```

   建構前相依性注射  
   ```
   public Component(@Value("${path}") String path) {
   }
   ```

提醒
====
Springframework 相依性注射相當方便，但也是一種毒藥。像是使用 @Value 這樣的注射方式後，相關的 bean 從頭到尾都需要 @Autowired。
